name: Label Pull Request
on:
  pull_request:
    types: [ 'opened' ]
jobs:
  merge-develop-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - run: echo "✅ Starting process add label"
      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
        with:
          labels: bug
      - run: echo "🍏 This job's status is ${{ job.status }}."
